### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by ocharles** [diagrams/diagrams-solve#6]
`HEAD` builds on GHC 8.8, but the latest Hackage release doesn't. Could we get a new release?

**Comment by byorgey** [comment]
Apologies for the radio silence on my end. I'm currently working through a big backlog of upper bounds bumps etc., hopefully within the next few days everything in the diagrams ecosystem should be updated for GHC 8.8.

**Comment by ocharles** [comment]
No problem! There's no rush from my side, I'm mostly creating issues to track progress.

**Comment by byorgey** [comment]
`diagrams-solve` has been updated for a while now, looks like I forgot to close this ticket.
